### ISSUE TITLE
Darker than Path Tracing

### ISSUE THREAD

**Issue by Pommpy** [SirKero/RTProgressivePhotonMapper#1]
Hi,

I've noticed that RTPM is darker than Path Tracing in the scene veachBiDir (and also in other scenes). The following images show the darker regions. Do you have any clues why it happens? I've also implemented a Photon Mapper in Falcor and got the same dark results as RTPM.

![image](https://github.com/SirKero/RTProgressivePhotonMapper/assets/81510000/b50faa0a-04fa-464c-b686-85569071f340)

![image](https://github.com/SirKero/RTProgressivePhotonMapper/assets/81510000/3fc0f124-4822-4b03-b82a-d75c37ebc92c)

**Comment by SirKero** [comment]
This occurs because Falcor also multiplies NdotL in the bsdf.eval function and photon mapping does not need multiplication with NdotL during collection as the photons are already cosine distributed. 
Easiest way to fix this is to divide the radiance by NdotL. E.g. change in `PhotonMapperCollect.rt.slang`:
` 132   rayData.radiance += f_r * photon.flux.xyz;`
to
`if(NdotL > 0)`
`    rayData.radiance += (f_r * photon.flux.xyz) / NdotL`

I will fix this within the next few days.

**Comment by SirKero** [comment]
Should now be fixed. In addition to the mentioned error, there was also an error with the generation PDFs.

RTPM:
![RTPM_BiDir ToneMapper dst 10172](https://github.com/SirKero/RTProgressivePhotonMapper/assets/19938496/4cf2dd17-81c9-498e-b687-f508a8660e1f)

Path Tracer:
![Path_BiDir ToneMapper dst 16194](https://github.com/SirKero/RTProgressivePhotonMapper/assets/19938496/a69c86a6-c0e8-4305-a081-08358d04bbae)
